version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 10
    labels:
      - type/dependencies
      - github_actions
    commit-message:
      prefix: chore(deps-dev)