name: Docker build & push template

on:
  workflow_call:
    inputs:
      work-dir:
        required: true
        type: string
      dockerfile:
        default: "Dockerfile"
        type: string
      image-name:
        required: true
        type: string
    secrets:
      dockerhub-username:
        required: true
      dockerhub-password:
        required: true

jobs:
  build-push:
    name: Build & push 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Create docker meta
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image-name }}
          tags: |
            type=sha,format=long,prefix=
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-password }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.work-dir }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ inputs.work-dir }}/${{ inputs.dockerfile }}
